/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fsu.instrumentation;

import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        AgentLoader classUnderTest = new AgentLoader();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
